### ISSUE TITLE
VolPostBuild throws dependency error for Android project

### ISSUE THREAD

**Issue by Jotamaza** [Volograms/volograms_unity_plugin#16]
Importing the unitypackage in an Android project throws an error with the UnityEditor.iOS.Xcode import.

Just added an #if UNITY_IOS to the whole class as a workaround.

- Unity version: 2020.3.21f1 Win
- Toolkit version: 0.1.1

**Comment by patrick-volograms** [comment]
Hi @Jotamaza, this change will be included in the next version of the unitypackage. Thank you very much for the report.

**Comment by patrick-volograms** [comment]
Fixed in unity package 0.12: https://github.com/Volograms/volograms_unity_plugin/releases/tag/0.12
