### ISSUE TITLE
[BUG] Vologram not appearing when used with a prefab on Android

### ISSUE THREAD

**Issue by patrick-volograms** [Volograms/volograms_unity_plugin#20]
**Describe the bug**
From Discord: 

> Hey guys, Im trying to enable the placement of a vologram within my scene based off of the AR Foundation tracked Image Manager. If the image is detected then the vologram should be placed etc... so basically image based detection. I seem to be having an issue though, Im not sure if saving a vologram object as a prefab to be placed is supported, but when the trigger is detected the vologram dosnt seem to appear? An object is definitely being placed within the scene as the vologram audio is playing etc, but its as if the mesh of the vologram just dosn't appear

**To Reproduce**
1. Create a prefab containing the VolPlayer component 
2. Write a script that adds the prefab to the scene
3. Build the scene and run on an Android device 
4. The vologram is placed but it is not visible

**Expected behavior**
Following the steps above, the vologram should be visible

**Comment by patrick-volograms** [comment]
After debug logging enabled these error messages appeared:

![Capture](https://user-images.githubusercontent.com/68862565/168579357-3895f17f-e5e9-43b7-a4a1-f950ecc07c05.JPG)

Volograms used were: joyce_2022 and TCD_Ulysses_sd

**Comment by capnramses** [comment]
I've been working on this and found the key problem - the vol_libs library code underpinning this plugin's playback is using low-level file functions that are on some systems still 32-bits. That means they can break with files over 2GB.

I have been testing some replacement code using 64-bit versions of those functions. That appears to work on at least Windows and Linux, so I expect similar behaviour on macOS and iOS and Android.

I'll be adding that improvement to the https://github.com/Volograms/vol_libs project over the next days.
This may take a while as we need to thoroughly test this as it will impact several projects, including the Volu app.
There may be other libraries and tools affected but we will know shortly.

**Comment by capnramses** [comment]
PR tested and merged -> Release coming shortly ~ tomorrow.
