### ISSUE TITLE
Vol playing in Play mode 

### ISSUE THREAD

**Issue by Jordan-s11** [Volograms/volograms_unity_plugin#8]
Cannot get Unity Volu plugin to work. Using one of the default volus from the app (the horse).
**To Reproduce**
1. Open empty project
2. import Volu plugin
3. Attach VolPlayer script an empty gameobject 
4. Assign paths to vol files
5. Press play
6. See that Vol is not playing

**Expected behavior**

**Screenshots**
![Screenshot 2022-03-15 104302](https://user-images.githubusercontent.com/97127853/158439292-4dcb4750-c771-4153-bc76-3ea53c1b53ac.png)

 - PC build mode in Unity
 - Windows 10
 - Unity Version 2021.1.24f

**Additional context**
- Unity plugin created 21 days from this report
- Vologram(s) used - Horse vol from the app
- Vologram Mesh Resolution

**Comment by capnramses** [comment]
thanks @Jordan-s11 . we have discussed this issue this morning, and we think it's likely due to using an older vologram capture that doesn't support the newer lighting and normals feature set.

we will reproduce the issue with the horse mask vologram - thank you for the specific details - and then provide a newer sample to try, and update our documentation accordingly if that solves the problem.

**Comment by patrick-volograms** [comment]
Hi @Jordan-s11. Thank you for your report. 

I played the horse vologram without issue on Mac so there may be an issue with our windows plugin. Could you activate the `Debugging Logging Options` at the bottom of the VolPlayer component and run your project? This might highlight the issue. 

https://github.com/Volograms/volograms_unity_plugin/wiki/Activating-Debug-Logging

**Comment by Jordan-s11** [comment]
Thank you for your responses,

I will try out the Debugging Logging options first thing tomorrow.

Regards

**Comment by capnramses** [comment]
Hi @Jordan-s11 - just wondering if you've had a chance to give it another go and get some log details?

**Comment by capnramses** [comment]
I think what we'll do here for general first-time snags is make a video tutorial to show the first-time setup procedure,
and possibly also add a sample scene/demo/vologram to this repository.

If you come back to this and find the logs we can re-open this and address any specific bug in there.
